# Generated by Django 5.1.6 on 2025-04-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reponses_Sickle_Cell_Anemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oneforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('twoforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('threeforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('fourforme1', models.CharField(choices=[('African', 'African'), ('Meditterranian', 'Mediterranean'), ('Middle_East', 'Middle East'), ('Other', 'Other')], max_length=50)),
                ('fiveforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('sixforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('sevenforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('eightforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('nineforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('tenforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('elevenforme1', models.CharField(choices=[('HbA', 'HbA'), ('HbS', 'HbS'), ('Other', 'Other')], max_length=50)),
                ('twelveforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('thirteenforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('fourteenforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('fifteenforme1', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SickleCellResult',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('responses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
